#!/bin/bash 

#SBATCH -p serial_requeue  #Partition to submit to 
#SBATCH -n 1  #Number of cores 
#SBATCH --gres=gpu
#SBATCH -t 30  #Runtime in minutes 
#SBATCH --mem-per-cpu=100000 #Memory per cpu in MB (see also --mem) 
#SBATCH --constraint=cuda-7.5

###module load hpc/cuda-3.2-RC2
#module load hpc/cuda-5.0.35

source new-modules.sh
module load cuda/7.5-fasrc01

make

time ./square 100000 > out-cuda.txt
